### ISSUE TITLE
AFTER INSERTING CHANNEL ID ,NOTHING HAPPENS 

### ISSUE THREAD

**Issue by asutoosh** [seaneustace/Youtube-Api-First-Commenter#1]
DONE WITH ALLL THE THINGS ! BUT WHEN I ENTER CHANNEL ID AT LAST , nothing happens.

**Comment by seaneustace** [comment]
You likely arent putting in the correct channel id, use the following tool:

https://commentpicker.com/youtube-channel-id.php

**Comment by asutoosh** [comment]
thanks for the info ! actually it's my mistake ! At last step I was inserting channel id , but was changing the starting UC as UU as I was testing other bots(there are instuctions like this to change channel id !
![image](https://github.com/seaneustace/Youtube-Api-First-Commenter/assets/85726810/f5e1e36b-ea9f-4934-a8f8-ccfd6fd41077)
Now Its working for me .
